<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->truncate();
        DB::table('currencies')->insert([
            ['country' => 'Albania', 'code' => 'ALL'],
            ['country' => 'America', 'code' => 'USD'],
            ['country' => 'Afghanistan', 'code' => 'AF'],
            ['country' => 'Argentina', 'code' => 'ARS'],
            ['country' => 'Aruba', 'code' => 'AWG'],
            ['country' => 'Australia', 'code' => 'AUD'],
            ['country' => 'Azerbaijan', 'code' => 'AZ'],
            ['country' => 'Bahamas', 'code' => 'BSD'],
            ['country' => 'Barbados', 'code' => 'BBD'],
            ['country' => 'Belarus', 'code' => 'BYR'],
            ['country' => 'Belgium', 'code' => 'EUR'],
            ['country' => 'Beliz', 'code' => 'BZD'],
            ['country' => 'Bermuda', 'code' => 'BMD'],
            ['country' => 'Bolivia', 'code' => 'BOB'],
            ['country' => 'Bosnia and Herzegovina', 'code' => 'BAM'],
            ['country' => 'Botswana', 'code' => 'BWP'],
            ['country' => 'Bulgaria', 'code' => 'BG'],
            ['country' => 'Brazil', 'code' => 'BRL'],
            ['country' => 'Britain (United Kingdom)', 'code' => 'GBP'],
            ['country' => 'Brunei Darussalam', 'code' => 'BND'],
            ['country' => 'Cambodia', 'code' => 'KHR'],
            ['country' => 'Canada', 'code' => 'CAD'],
            ['country' => 'Cayman Islands', 'code' => 'KYD'],
            ['country' => 'Chile', 'code' => 'CLP'],
            ['country' => 'China', 'code' => 'CNY'],
            ['country' => 'Colombia', 'code' => 'COP'],
            ['country' => 'Costa Rica', 'code' => 'CRC'],
            ['country' => 'Croatia', 'code' => 'HRK'],
            ['country' => 'Cuba', 'code' => 'CUP'],
            ['country' => 'Cyprus', 'code' => 'EUR'],
            ['country' => 'Czech Republic', 'code' => 'CZK'],
            ['country' => 'Denmark', 'code' => 'DKK'],
            ['country' => 'Dominican Republic', 'code' => 'DOP '],
            ['country' => 'East Caribbean', 'code' => 'XCD'],
            ['country' => 'Egypt', 'code' => 'EGP'],
            ['country' => 'El Salvador', 'code' => 'SVC'],
            ['country' => 'England (United Kingdom)', 'code' => 'GBP'],
            ['country' => 'Euro', 'code' => 'EUR'],
            ['country' => 'Falkland Islands', 'code' => 'FKP'],
            ['country' => 'Fiji', 'code' => 'FJD'],
            ['country' => 'France', 'code' => 'EUR'],
            ['country' => 'Ghana', 'code' => 'GHC'],
            ['country' => 'Gibraltar', 'code' => 'GIP'],
            ['country' => 'Greece', 'code' => 'EUR'],
            ['country' => 'Guatemala', 'code' => 'GTQ'],
            ['country' => 'Guernsey', 'code' => 'GGP'],
            ['country' => 'Guyana', 'code' => 'GYD'],
            ['country' => 'Holland (Netherlands)', 'code' => 'EUR'],
            ['country' => 'Honduras', 'code' => 'HNL'],
            ['country' => 'Hong Kong', 'code' => 'HKD'],
            ['country' => 'Hungary', 'code' => 'HUF'],
            ['country' => 'Iceland', 'code' => 'ISK'],
            ['country' => 'India', 'code' => 'INR'],
            ['country' => 'Indonesia', 'code' => 'IDR'],
            ['country' => 'Iran', 'code' => 'IRR'],
            ['country' => 'Ireland', 'code' => 'EUR'],
            ['country' => 'Isle of Man', 'code' => 'IMP'],
            ['country' => 'Israel', 'code' => 'ILS'],
            ['country' => 'Italy', 'code' => 'EUR'],
            ['country' => 'Jamaica', 'code' => 'JMD'],
            ['country' => 'Japan', 'code' => 'JPY'],
            ['country' => 'Jersey', 'code' => 'JEP'],
            ['country' => 'Kazakhstan', 'code' => 'KZT'],
            ['country' => 'Korea (North)', 'code' => 'KPW'],
            ['country' => 'Korea (South)', 'code' => 'KRW'],
            ['country' => 'Kyrgyzstan', 'code' => 'KGS'],
            ['country' => 'Laos', 'code' => 'LAK'],
            ['country' => 'Latvia', 'code' => 'LVL'],
            ['country' => 'Lebanon', 'code' => 'LBP'],
            ['country' => 'Liberia', 'code' => 'LRD'],
            ['country' => 'Liechtenstein', 'code' => 'CHF'],
            ['country' => 'Lithuania', 'code' => 'LTL'],
            ['country' => 'Luxembourg', 'code' => 'EUR'],
            ['country' => 'Macedonia', 'code' => 'MKD'],
            ['country' => 'Malaysia', 'code' => 'MYR'],
            ['country' => 'Malta', 'code' => 'EUR'],
            ['country' => 'Mauritius', 'code' => 'MUR'],
            ['country' => 'Mexico', 'code' => 'MX'],
            ['country' => 'Mongolia', 'code' => 'MNT'],
            ['country' => 'Mozambique', 'code' => 'MZ'],
            ['country' => 'Namibia', 'code' => 'NAD'],
            ['country' => 'Nepal', 'code' => 'NPR'],
            ['country' => 'Netherlands Antilles', 'code' => 'ANG'],
            ['country' => 'Netherlands', 'code' => 'EUR'],
            ['country' => 'New Zealand', 'code' => 'NZD'],
            ['country' => 'Nicaragua', 'code' => 'NIO'],
            ['country' => 'Nigeria', 'code' => 'NG'],
            ['country' => 'North Korea', 'code' => 'KPW'],
            ['country' => 'Norway', 'code' => 'NOK'],
            ['country' => 'Oman', 'code' => 'OMR'],
            ['country' => 'Pakistan', 'code' => 'PKR'],
            ['country' => 'Panama', 'code' => 'PAB'],
            ['country' => 'Paraguay', 'code' => 'PYG'],
            ['country' => 'Peru', 'code' => 'PE'],
            ['country' => 'Philippines', 'code' => 'PHP'],
            ['country' => 'Poland', 'code' => 'PL'],
            ['country' => 'Qatar', 'code' => 'QAR'],
            ['country' => 'Romania', 'code' => 'RO'],
            ['country' => 'Russia', 'code' => 'RUB'],
            ['country' => 'Saint Helena', 'code' => 'SHP'],
            ['country' => 'Saudi Arabia', 'code' => 'SAR'],
            ['country' => 'Serbia', 'code' => 'RSD'],
            ['country' => 'Seychelles', 'code' => 'SCR'],
            ['country' => 'Singapore', 'code' => 'SGD'],
            ['country' => 'Slovenia', 'code' => 'EUR'],
            ['country' => 'Solomon Islands', 'code' => 'SBD'],
            ['country' => 'Somalia', 'code' => 'SOS'],
            ['country' => 'South Africa', 'code' => 'ZAR'],
            ['country' => 'South Korea', 'code' => 'KRW'],
            ['country' => 'Spain', 'code' => 'EUR'],
            ['country' => 'Sri Lanka', 'code' => 'LKR'],
            ['country' => 'Sweden', 'code' => 'SEK'],
            ['country' => 'Switzerland', 'code' => 'CHF'],
            ['country' => 'Suriname', 'code' => 'SRD'],
            ['country' => 'Syria', 'code' => 'SYP'],
            ['country' => 'Taiwan', 'code' => 'TWD'],
            ['country' => 'Thailand', 'code' => 'THB'],
            ['country' => 'Trinidad and Tobago', 'code' => 'TTD'],
            ['country' => 'Turkey', 'code' => 'TRY'],
            ['country' => 'Turkey', 'code' => 'TRL'],
            ['country' => 'Tuvalu', 'code' => 'TVD'],
            ['country' => 'Ukraine', 'code' => 'UAH'],
            ['country' => 'United Kingdom', 'code' => 'GBP'],
            ['country' => 'United States of America', 'code' => 'USD'],
            ['country' => 'Uruguay', 'code' => 'UYU'],
            ['country' => 'Uzbekistan', 'code' => 'UZS'],
            ['country' => 'Vatican City', 'code' => 'EUR'],
            ['country' => 'Venezuela', 'code' => 'VEF'],
            ['country' => 'Vietnam', 'code' => 'VND'],
            ['country' => 'Yemen', 'code' => 'YER'],
            ['country' => 'Zimbabwe', 'code' => 'ZWD']
        ]);
    }
}
