INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (1, 'Albania', 'ALL', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (2, 'America', 'USD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (3, 'Afghanistan', 'AF', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (4, 'Argentina', 'ARS', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (5, 'Aruba', 'AWG', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (6, 'Australia', 'AUD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (7, 'Azerbaijan', 'AZ', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (8, 'Bahamas', 'BSD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (9, 'Barbados', 'BBD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (10, 'Belarus', 'BYR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (11, 'Belgium', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (12, 'Beliz', 'BZD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (13, 'Bermuda', 'BMD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (14, 'Bolivia', 'BOB', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (15, 'Bosnia and Herzegovina', 'BAM', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (16, 'Botswana', 'BWP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (17, 'Bulgaria', 'BG', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (18, 'Brazil', 'BRL', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (19, 'Britain (United Kingdom)', 'GBP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (20, 'Brunei Darussalam', 'BND', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (21, 'Cambodia', 'KHR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (22, 'Canada', 'CAD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (23, 'Cayman Islands', 'KYD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (24, 'Chile', 'CLP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (25, 'China', 'CNY', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (26, 'Colombia', 'COP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (27, 'Costa Rica', 'CRC', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (28, 'Croatia', 'HRK', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (29, 'Cuba', 'CUP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (30, 'Cyprus', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (31, 'Czech Republic', 'CZK', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (32, 'Denmark', 'DKK', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (33, 'Dominican Republic', 'DOP ', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (34, 'East Caribbean', 'XCD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (35, 'Egypt', 'EGP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (36, 'El Salvador', 'SVC', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (37, 'England (United Kingdom)', 'GBP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (38, 'Euro', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (39, 'Falkland Islands', 'FKP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (40, 'Fiji', 'FJD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (41, 'France', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (42, 'Ghana', 'GHC', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (43, 'Gibraltar', 'GIP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (44, 'Greece', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (45, 'Guatemala', 'GTQ', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (46, 'Guernsey', 'GGP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (47, 'Guyana', 'GYD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (48, 'Holland (Netherlands)', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (49, 'Honduras', 'HNL', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (50, 'Hong Kong', 'HKD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (51, 'Hungary', 'HUF', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (52, 'Iceland', 'ISK', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (53, 'India', 'INR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (54, 'Indonesia', 'IDR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (55, 'Iran', 'IRR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (56, 'Ireland', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (57, 'Isle of Man', 'IMP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (58, 'Israel', 'ILS', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (59, 'Italy', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (60, 'Jamaica', 'JMD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (61, 'Japan', 'JPY', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (62, 'Jersey', 'JEP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (63, 'Kazakhstan', 'KZT', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (64, 'Korea (North)', 'KPW', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (65, 'Korea (South)', 'KRW', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (66, 'Kyrgyzstan', 'KGS', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (67, 'Laos', 'LAK', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (68, 'Latvia', 'LVL', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (69, 'Lebanon', 'LBP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (70, 'Liberia', 'LRD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (71, 'Liechtenstein', 'CHF', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (72, 'Lithuania', 'LTL', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (73, 'Luxembourg', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (74, 'Macedonia', 'MKD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (75, 'Malaysia', 'MYR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (76, 'Malta', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (77, 'Mauritius', 'MUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (78, 'Mexico', 'MX', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (79, 'Mongolia', 'MNT', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (80, 'Mozambique', 'MZ', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (81, 'Namibia', 'NAD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (82, 'Nepal', 'NPR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (83, 'Netherlands Antilles', 'ANG', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (84, 'Netherlands', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (85, 'New Zealand', 'NZD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (86, 'Nicaragua', 'NIO', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (87, 'Nigeria', 'NG', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (88, 'North Korea', 'KPW', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (89, 'Norway', 'NOK', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (90, 'Oman', 'OMR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (91, 'Pakistan', 'PKR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (92, 'Panama', 'PAB', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (93, 'Paraguay', 'PYG', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (94, 'Peru', 'PE', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (95, 'Philippines', 'PHP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (96, 'Poland', 'PL', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (97, 'Qatar', 'QAR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (98, 'Romania', 'RO', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (99, 'Russia', 'RUB', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (100, 'Saint Helena', 'SHP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (101, 'Saudi Arabia', 'SAR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (102, 'Serbia', 'RSD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (103, 'Seychelles', 'SCR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (104, 'Singapore', 'SGD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (105, 'Slovenia', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (106, 'Solomon Islands', 'SBD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (107, 'Somalia', 'SOS', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (108, 'South Africa', 'ZAR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (109, 'South Korea', 'KRW', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (110, 'Spain', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (111, 'Sri Lanka', 'LKR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (112, 'Sweden', 'SEK', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (113, 'Switzerland', 'CHF', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (114, 'Suriname', 'SRD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (115, 'Syria', 'SYP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (116, 'Taiwan', 'TWD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (117, 'Thailand', 'THB', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (118, 'Trinidad and Tobago', 'TTD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (119, 'Turkey', 'TRY', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (120, 'Turkey', 'TRL', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (121, 'Tuvalu', 'TVD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (122, 'Ukraine', 'UAH', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (123, 'United Kingdom', 'GBP', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (124, 'United States of America', 'USD', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (125, 'Uruguay', 'UYU', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (126, 'Uzbekistan', 'UZS', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (127, 'Vatican City', 'EUR', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (128, 'Venezuela', 'VEF', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (129, 'Vietnam', 'VND', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (130, 'Yemen', 'YER', null, null);
INSERT INTO financial.currencies (currency_id, country, code, created_at, updated_at) VALUES (131, 'Zimbabwe', 'ZWD', null, null);