INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ADP', 'Andorran Peseta', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('AED', 'United Arab Emirates Dirham', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('AFA', 'Afghanistan Afghani', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ALL', 'Albanian Lek', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('AMD', 'Armenian Dram', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ANG', 'Netherlands Antillian Guilder', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('AOK', 'Angolan Kwanza', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ARS', 'Argentine Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('AUD', 'Australian Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('AWG', 'Aruban Florin', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BBD', 'Barbados Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BDT', 'Bangladeshi Taka', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BGN', 'Bulgarian Lev', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BHD', 'Bahraini Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BIF', 'Burundi Franc', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BMD', 'Bermudian Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BND', 'Brunei Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BOB', 'Bolivian Boliviano', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BRL', 'Brazilian Real', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BSD', 'Bahamian Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BTN', 'Bhutan Ngultrum', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BUK', 'Burma Kyat', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BWP', 'Botswanian Pula', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('BZD', 'Belize Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CAD', 'Canadian Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CHF', 'Swiss Franc', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CLF', 'Chilean Unidades de Fomento', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CLP', 'Chilean Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CNY', 'Yuan (Chinese) Renminbi', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('COP', 'Colombian Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CRC', 'Costa Rican Colon', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CUP', 'Cuban Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CVE', 'Cape Verde Escudo', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CYP', 'Cyprus Pound', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('CZK', 'Czech Republic Koruna', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('DKK', 'Danish Krone', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('DOP', 'Dominican Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('DZD', 'Algerian Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ECS', 'Ecuador Sucre', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('EEK', 'Estonian Kroon (EEK)', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('EGP', 'Egyptian Pound', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ETB', 'Ethiopian Birr', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('EUR', 'Euro', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('FJD', 'Fiji Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('FKP', 'Falkland Islands Pound', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('GBP', 'British Pound', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('GHC', 'Ghanaian Cedi', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('GIP', 'Gibraltar Pound', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('GMD', 'Gambian Dalasi', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('GNF', 'Guinea Franc', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('GTQ', 'Guatemalan Quetzal', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('GWP', 'Guinea-Bissau Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('GYD', 'Guyanan Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('HKD', 'Hong Kong Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('HNL', 'Honduran Lempira', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('HTG', 'Haitian Gourde', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('HUF', 'Hungarian Forint', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('IDR', 'Indonesian Rupiah', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('IEP', 'Irish Punt', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ILS', 'Israeli Shekel', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('INR', 'Indian Rupee', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('IQD', 'Iraqi Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('IRR', 'Iranian Rial', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('JMD', 'Jamaican Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('JOD', 'Jordanian Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('JPY', 'Japanese Yen', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('KES', 'Kenyan Schilling', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('KHR', 'Kampuchean (Cambodian) Riel', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('KMF', 'Comoros Franc', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('KPW', 'North Korean Won', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('KRW', '(South) Korean Won', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('KWD', 'Kuwaiti Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('KYD', 'Cayman Islands Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('LAK', 'Lao Kip', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('LBP', 'Lebanese Pound', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('LKR', 'Sri Lanka Rupee', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('LRD', 'Liberian Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('LSL', 'Lesotho Loti', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('LYD', 'Libyan Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MAD', 'Moroccan Dirham', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MGF', 'Malagasy Franc', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MNT', 'Mongolian Tugrik', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MOP', 'Macau Pataca', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MRO', 'Mauritanian Ouguiya', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MTL', 'Maltese Lira', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MUR', 'Mauritius Rupee', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MVR', 'Maldive Rufiyaa', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MWK', 'Malawi Kwacha', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MXP', 'Mexican Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MYR', 'Malaysian Ringgit', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('MZM', 'Mozambique Metical', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('NAD', 'Namibian Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('NGN', 'Nigerian Naira', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('NIO', 'Nicaraguan Cordoba', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('NOK', 'Norwegian Kroner', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('NPR', 'Nepalese Rupee', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('NZD', 'New Zealand Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('OMR', 'Omani Rial', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('PAB', 'Panamanian Balboa', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('PEN', 'Peruvian Nuevo Sol', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('PGK', 'Papua New Guinea Kina', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('PHP', 'Philippine Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('PKR', 'Pakistan Rupee', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('PLN', 'Polish Zloty', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('PYG', 'Paraguay Guarani', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('QAR', 'Qatari Rial', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('RON', 'Romanian Leu', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('RUB', 'Russian Ruble', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('RWF', 'Rwanda Franc', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SAR', 'Saudi Arabian Riyal', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SBD', 'Solomon Islands Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SCR', 'Seychelles Rupee', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SDP', 'Sudanese Pound', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SEK', 'Swedish Krona', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SGD', 'Singapore Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SHP', 'St. Helena Pound', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SKK', 'Slovak Koruna', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SLL', 'Sierra Leone Leone', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SOS', 'Somali Schilling', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SRG', 'Suriname Guilder', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('STD', 'Sao Tome and Principe Dobra', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SVC', 'El Salvador Colon', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SYP', 'Syrian Potmd', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('SZL', 'Swaziland Lilangeni', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('THB', 'Thai Baht', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('TND', 'Tunisian Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('TOP', 'Tongan Paanga', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('TPE', 'East Timor Escudo', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('TRY', 'Turkish Lira', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('TTD', 'Trinidad and Tobago Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('TWD', 'Taiwan Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('TZS', 'Tanzanian Schilling', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('UGX', 'Uganda Shilling', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('USD', 'US Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('UYU', 'Uruguayan Peso', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('VEF', 'Venezualan Bolivar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('VND', 'Vietnamese Dong', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('VUV', 'Vanuatu Vatu', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('WST', 'Samoan Tala', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XAF', 'Communauté Financière Africaine BEAC, Francs', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XAG', 'Silver, Ounces', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XAU', 'Gold, Ounces', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XCD', 'East Caribbean Dollar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XDR', 'International Monetary Fund (IMF) Special Drawing Rights', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XOF', 'Communauté Financière Africaine BCEAO - Francs', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XPD', 'Palladium Ounces', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XPF', 'Comptoirs Français du Pacifique Francs', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('XPT', 'Platinum, Ounces', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('YDD', 'Democratic Yemeni Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('YER', 'Yemeni Rial', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('YUD', 'New Yugoslavia Dinar', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ZAR', 'South African Rand', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ZMK', 'Zambian Kwacha', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ZRZ', 'Zaire Zaire', null, null);
INSERT INTO financial.currencies (currency_id, currency_name, created_at, updated_at) VALUES ('ZWD', 'Zimbabwe Dollar', null, null);